### ISSUE TITLE
"Normalise" AlmostNormal surfaces

### ISSUE THREAD

**Issue by WPettersson** [regina-normal/regina#33]
For any triangulation T of a manifold M with an almost normal surface S, it is easy to use one 0-2 move and some normal isotopy for each octagon or tube to create a new triangulation T' of M with a normal surface S' which is isotopic to S.

We only deal with octagons in Regina, so tubes don't have to be involved at all. Is there any reason to not go ahead and create this feature? I figure it'd work like "Crush along a normal surface" except it would be "Create normal surface from this almost normal surface", and would produce a new Triangulation object.

The point of this is building the framework to code up a new hyperbolicity test that's being worked on with some collaborators, but I'm taking small steps to start with.

**Comment by WPettersson** [comment]
I've pushed the normalise-ans branch, which doesn't yet actually normalise, but adds support for 0-2 moves to Regina. There's the C++ code in the engine, test cases for C++, python bindings, and support in the QtUI. There are no python test cases, as python doesn't have test cases for other elt. moves either.

For the QtUI, I added a TetIntChooser class to let the user choose a tetrahedron and integer (0-5) for the edge. Since every edge is valid for a 0-2 move, the number of options gets large quickly. To combat this, I broke the selections into two combo boxes, one for tetrahedron and one for integer. This class should be suitably generic, if we ever need it again.

While I'm in eltmovedialog3.cpp, there's references to ID_XXX for the various moves, but these seem to have no real use at the moment. They're passed into addButton to assign an ID to each button, but this ID seems to never be referenced again.
Is there a need for these? If not, can we re-purpose them? The radio buttons and combo boxes are added to a QGridLayout in grid locations specified by indices directly,i.e. 
```
addWidget(boxShellBdry, 10, 0)
````
It'd be easier to add new items if we could use these IDs here, i.e. 
```
addWidget(boxShellBdry, ID_SHELLBDRY, 0)
```
This would make it slightly easier to add new moves (or even just shuffle the current ones around). If this seems reasonable, I can do this fix in my branch as well.

**Comment by WPettersson** [comment]
So the `Triangulation<3> * removeOcts()` function is fairly simple, and currently I've just put it in NSVectorANStandard. I realise that NSVectorQuadOct also has octs, but I'm fairly confident that it's impossible to "normalise" those into just quads. We could always go the route of normalising QuadOct to standard tri-quad though.

Should `removeOcts()` (name changes readily accepted) just exist in NSVectorANStandard, or should we put a virtual version of it into NormalSurface? I'm leaning towards having it in NormalSurface, myself.

Also, currently I'm just creating the new triangulation, and nothing else. It is fairly trivial to also add in the normal surface in the new triangulation that is isotopic to the original normal surface that had octs. Personally, having the new normal surface automatically would be easier, but it's not something that would be hugely important. I'm thinking a bool flag `createNewSurface` which, if true, tells `removeOcts()` to also create the new surface attached to the new triangulation. Does that sound reasonable?

**Comment by WPettersson** [comment]
Well, I worked on this some more, and I think `removeOctagons()` has to live in NormalSurface, the various vector-based classes don't know the underlying triangulation. I'm also curious as to what we should call this option in the GUI. `Remove Octagons` is only marginally correct. We don't remove octagons from a surface, we create a new triangulation which will have a normal surface isotopic to the original that has no octagons in the new triangulation. But "Remove Octagons" is the best way I can phrase that. Happy to rename.

Now pushed to normalise-ans @6c7c2cab3b10749778d8602ce9dfc0b2d5056216

**Comment by baburton** [comment]
Hi - so this response was five years coming, apologies :/ In the meantime the normal surface code has been completely reorganised (as part of regina 7.0), and the vector subclasses were replaced with a flatter class structure plus a new concept of encodings.

Anyway: the functionality you want is now present (as of recent commits today). It's done a little differently though:

- I didn't use your zeroTwoMove(), since there is already a more general suite of zeroTwoMove() functions that were not present when you wrote your original patch.
- Having said that, I've implemented NormalSurface::removeOcts() in a way that does not actually call zeroTwoMove(). Instead it just subdivides each original tetrahedron in its own implementation in what is essentially an equivalent way. This is a bit more streamlined, but also importantly it avoids having to make promises in the zeroTwoMove() API about how moves will label the new tetrahedra and their vertices.
- I've written it so that it can handle multiple octagons, and/or multiple tetrahedra with octagons.
- The implementation can handle quad-oct coordinates as well as standard almost normal coordinates (this involves some playing with the vector encodings, which did not exist when you wrote your patch).
- The implementation also constructs the modified normal surface, so you don't need to search for it later. In fact, the routine *only* returns this surface, not the modified triangulation (since you can now get to the modified triangulation via the triangulation() function, even though it's not in the packet tree - again something that was not possible five years ago when you wrote your patch).

As a corollary to all of this, I've also expanded NormalSurface::cutAlong() to support almost normal surfaces (which perhaps was the reason you wanted this in the first place, or perhaps not?).

Again, sorry this took so long (but I'm glad I did this after the 7.0 overhaul and not before).

Closing this now (but please reopen if there's something you want that's missing from my code) - Ben.
