### ISSUE TITLE
Census name

### ISSUE THREAD

**Issue by bobbycyiii** [regina-normal/regina#45]
The GUI's Open Example tab menu says the knot and link complement census is of hyperbolic knot and link complements. But L310066 is a graph manifold. It should read "Knot / Link Complements."

**Comment by WPettersson** [comment]
This now has a fix in the fix-census-name branch, will be included in 6.0 release.

**Comment by baburton** [comment]
I've looked into this some more, and I think the solution is to drop this census entirely.

There are 27 triangulations in this census that I cannot quickly prove to be hyperbolic, and although I have not yet tried to verify non-hyperbolicity, it does appear likely that many (and possibly all) of these are non-hyperbolic. In particular, just the counts suggest that Christy included torus knots with 8-11 crossings (but not 3-7 crossings). Even then there are still too many 10-crossing knots, and further digging shows the duplicate Perko pair is present (L110161, L110162).

So: rather than try to fix this, I think I will drop this census completely and replace it data from with my own knot tabulation (which means we lose the multiple-component links, but we gain both uniqueness and a sensible description of what's in the census).

Now is probably a good time to do this anyway, since as of last month's release it is now possible to ship a census with actual knots as opposed to just their complements.

**Comment by baburton** [comment]
Done: I've replaced the Christy example file with a modern census of knots (realised as Link packets, not 3-manifolds), and in the census lookup routines I've kept it but renamed it as "Christy's collection of knot/link complements" to better indicate that it is not a proper census.
