### ISSUE TITLE
pybind11 interface: combining flags

### ISSUE THREAD

**Issue by NathanDunfield** [regina-normal/regina#51]
In the old boost-based Python interface, you could do:
```
 regina.NS_FUNDAMENTAL | regina.NS_EMBEDDED_ONLY
```
to combine flags.  However, with pybind11 in the current repo tip one has:
```
regina.NS_FUNDAMENTAL | regina.NS_EMBEDDED_ONLY
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-51f21cdcddac> in <module>()
----> 1 regina.NS_FUNDAMENTAL | regina.NS_EMBEDDED_ONLY

TypeError: unsupported operand type(s) for |: 'regina.engine.NormalListFlags' and 'regina.engine.NormalListFlags'
> <ipython-input-9-51f21cdcddac>(1)<module>()
----> 1 regina.NS_FUNDAMENTAL | regina.NS_EMBEDDED_ONLY
```
Presumably there's a way to have pybind11 make the ```__or__``` method of NormalListFlags do the expected thing.

**Comment by NathanDunfield** [comment]
Calling @baburton and @unhyperbolic.

**Comment by WPettersson** [comment]
I've found one fix (see commit above), which somewhat addresses this by creating an __or__ operator for each of the enums to promote the left hand side to NormalList/NormalAlg respectively. This lines up with the engine, where only the or operator promotes. Note that using pybind11::self | pybind11::self does not compile (not sure on exact reason), and the .def has to come after export_values(), as otherwise it demotes the pybind11::enum down to a pybind11::class which means it loses access to export_values().

Not sure if this is the correct way forward still, but it's one way forward.

**Comment by NathanDunfield** [comment]
@WPettersson Your fix works for me.  Suggest merging with master and closing this issue.

**Comment by NathanDunfield** [comment]
@WPettersson Thanks for fixing this!
