### ISSUE TITLE
6.0 release

### ISSUE THREAD

**Issue by WPettersson** [regina-normal/regina#55]
Created for discussion of 6.0 release.

**Comment by WPettersson** [comment]
There's now a pre-release tag for Regina 6.0, called 6.0_alpha. This is off the 6.0_pre branch, which is branched off master, and also has deprecations and MPI utilities removed.

**Comment by xnox** [comment]
Should I ship 6.0 alpha in ubuntu?

**Comment by WPettersson** [comment]
Everything bar the handbook should be up to date, the integrated tests work fine but I don't know if anyone has actually been using the pre-release for significant work. Feel free to ship it, and let us know if there are any bugs that we haven't noticed yet.

**Comment by xnox** [comment]
Seems fine so far on most architectures. I saw a segfault on armhf, retrying now. Possibly there is issue with unaligned access and/or 32bit architecture.

**Comment by baburton** [comment]
Hi Dimitri,

Should I ship 6.0 alpha in ubuntu?

Is there a freeze deadline coming up? (I had planned to get 6.0 proper out during lockdown, and if there’s a rush to meet a freeze deadline then I can try to clean things up. I need to put a new version into Debian also, since the old version has fallen out of the testing release due to its python2 dependency.)

Best regards - Ben.

--

Prof. Benjamin Burton
Computational Geometry & Topology Group
School of Mathematics and Physics
The University of Queensland, Australia

UQ ALLY   ::   Supporting and celebrating the diversity of sexuality, gender and sex at UQ.   Pronouns: He, him, his

**Comment by xnox** [comment]
No immediate deadlines. But it's good enough time for me to upload alpha. To see that it works with boost1.71, new icu, makes python2 fall out, doesn't fail on any arches, etc. In ubuntu this, is the last package holding up boost1.67 for example.

**Comment by baburton** [comment]
6.0 is out, so closing this now.
