### ISSUE TITLE
Regina pulls in system libnormaliz headers and binary library, causing "import regina" to fail in Python

### ISSUE THREAD

**Issue by NathanDunfield** [regina-normal/regina#73]
On a Ubuntu 20.04 box with gcc 9.3 and cmake 3.16.3, I have a "system" version of `libnormaliz` installed, including header files.  When I build Regina 7.0 in the usual way, I get the following error when doing `import regina` in Python:
```
ImportError: /sage/local/var/lib/sage/venv-python3.8/lib/python3.8/site-packages/regina/engine.so: undefined symbol: renf_elem_clear
```
Here, by "system", I mean `libnormaliz` is in the directories I specified by `CMAKE_INCLUDE_PATH` etc., which here were `/sage/local/include` etc.  The undefined symbol is listed as such in `/sage/local/lib/libnormaliz.so` and is supplied by its dependency library `libeantic.so`. 

I can fix this by temporarily renaming `/sage/local/include/libnormaliz` and then building Regina, but presumably there is a better fix.

Note this is new to 7.0, as this [Docker image](https://hub.docker.com/layers/computop/sage/9.5b7/images/sha256-4e364af835d291b3163) image has Regina 6.0 working fine, but compiling Regina 7.0 with:
```
# clone source to regina_src
cd regina_src/build
cmake -DCMAKE_PREFIX_PATH=$SAGE_LOCAL \
      -DCMAKE_INCLUDE_PATH=$SAGE_LOCAL/include \
      -DCMAKE_LIBRARY_PATH=$SAGE_LOCAL/lib \
      -DCMAKE_INSTALL_PREFIX=$SAGE_LOCAL \
      -DPython_EXECUTABLE=$SAGE_VENV/bin/python3 \
      -DDISABLE_GUI=1 -DREGINA_INSTALL_TYPE=XDG ..
make  install
sage -python -c "import regina"
```
will reproduce this issue.  So maybe some change in the cmake files is resulting in it being less cautious where it looks for the `libnormaliz` includes.

**Comment by NathanDunfield** [comment]
Unfortunately, I can't build that branch, here's the compiler error message I get:
```
In file included from /home/sage/regina/engine/triangulation/detail/boundarycomponent.h:50,
                 from /home/sage/regina/engine/triangulation/generic/boundarycomponent.h:46,
                 from /home/sage/regina/engine/triangulation/generic.h:46,
                 from /home/sage/regina/engine/triangulation/explicit/boundary6.cpp:33:
/home/sage/regina/engine/utilities/typeutils.h:210:25: error: ‘function’ is not a member of ‘std’
  210 | struct CallableArg<std::function<ReturnType(Args...)>, pos> {
      |                         ^~~~~~~~
/home/sage/regina/engine/utilities/typeutils.h:1:1: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
  +++ |+#include <functional>
    1 | 
/home/sage/regina/engine/utilities/typeutils.h:210:53: error: wrong number of template arguments (1, should be 2)
  210 | struct CallableArg<std::function<ReturnType(Args...)>, pos> {
      |                                                     ^
/home/sage/regina/engine/utilities/typeutils.h:180:8: note: provided for ‘template<class Action, int pos> struct regina::CallableArg’
  180 | struct CallableArg;
      |        ^~~~~~~~~~~
/home/sage/regina/engine/utilities/typeutils.h:214:25: error: ‘function’ is not a member of ‘std’
  214 | struct CallableArg<std::function<ReturnType(Args...)>&, pos> {
      |                         ^~~~~~~~
/home/sage/regina/engine/utilities/typeutils.h:214:25: note: ‘std::function’ is defined in header ‘<functional>’; did you forget to ‘#include <functional>’?
/home/sage/regina/engine/utilities/typeutils.h:214:53: error: wrong number of template arguments (1, should be 2)
  214 | struct CallableArg<std::function<ReturnType(Args...)>&, pos> {
      |                                                     ^
/home/sage/regina/engine/utilities/typeutils.h:180:8: note: provided for ‘template<class Action, int pos> struct regina::CallableArg’
  180 | struct CallableArg;
      |        ^~~~~~~~~~~
/home/sage/regina/engine/utilities/typeutils.h:214:55: error: expected unqualified-id before ‘,’ token
  214 | struct CallableArg<std::function<ReturnType(Args...)>&, pos> {
      |                                                       ^
/home/sage/regina/engine/utilities/typeutils.h:218:31: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
  218 | struct CallableArg<const std::function<ReturnType(Args...)>&, pos> {
      |                               ^~~~~~~~
/home/sage/regina/engine/utilities/typeutils.h:218:66: error: wrong number of template arguments (1, should be 2)
  218 | struct CallableArg<const std::function<ReturnType(Args...)>&, pos> {
      |                                                                  ^
/home/sage/regina/engine/utilities/typeutils.h:180:8: note: provided for ‘template<class Action, int pos> struct regina::CallableArg’
  180 | struct CallableArg;
      |        ^~~~~~~~~~~
make[2]: *** [engine/CMakeFiles/regina-engine.dir/build.make:3768: engine/CMakeFiles/regina-engine.dir/triangulation/explicit/boundary6.cpp.o] Error 1
```

**Comment by NathanDunfield** [comment]
Thanks, now it builds fine, but still get the same error when I try the Python import.  Possibly, this relates to the part of `regina/engine/libnormaliz/general.h` which checks for the presence of `eantic`.

**Comment by WPettersson** [comment]
That shouldn't be pulled in, because `ENFNORMALIZ` isn't defined and we even undefine it just in case. https://github.com/regina-normal/regina/blob/45a6a120420c5ec427824de0ff0144bdcea715f4/engine/libnormaliz/nmz_config.h#L5 

Clearly it is being pulled in though, so I need to work out why. I guess one lazy fix on our end might be to completely remove that section of that header, but without knowing the root cause, that might just lead to other issues.

**Comment by NathanDunfield** [comment]
The system version of `normaliz` does define `ENFNORMALIZ`.  So some part of `/sage/local/include/libnormaliz` is still being pulled in, I think.

**Comment by NathanDunfield** [comment]
In particular, deleting just the system file `/sage/local/include/libnormaliz/nmz_config.h` fixes the problem (previously, I was deleting all of `/sage/local/include/libnormaliz/` to fix it).

**Comment by baburton** [comment]
Hmm. So I’d be super happy with a fix that avoids the need to patch regina’s copy of libnormaliz (mainly because this makes Normaliz upgrades messier).

Will: do you know if there’s a way to add the local include path in the source tree *before* CMAKE_INCLUDE_PATH, so that they are found by <foo> also? This should be harmless (since regina’s own headers should take priority anyway), should avoid the stray sage/local includes that Nathan’s seeing, and should avoid any need to patch Normaliz. I hope.

- b.

**Comment by baburton** [comment]
Oh: also FYI, any patches should eventually go in the service-7.0 branch (which is basically 7.0 plus subsequent fixes like this, and which is what Nathan will probably be pulling from for the docker image). Once it’s all sorted we can then merge service-7.0 into master.

- b.

**Comment by WPettersson** [comment]
Annoyingly, the C++ spec loosely says that the search order for <foo> style includes is an implementation choice. I've checked both GCC (11.2.0) and clang (13.0.0) and they put anything specified on a command line before system include locations. Given the libnormaliz include structure, I think we would need to add "-I /path/to/engine" so that the files are correctly found, and that should work for g++ and clang++, but I haven't tested on Mac, Windows, and I haven't tested other compilers.

**Comment by baburton** [comment]
I’m happy with something that supports g++ and clang++.

On macOS, if you try to build “out of the box” at the command line, you’ll be using clang with cmake. There is also an Xcode project in the source tree, independent of the cmake setup, but you shouldn’t worry about that - it’s basically tailored to my own environment [*], and it won’t be affected by any changes to the cmake scripts.

On windows, the setup I’m using (and the only one I’m willing to spend time supporting) is msys2/mingw64, which is g++ (it was v10 a year ago, possibly v11 by now). In case anyone finds this message in the issue tracker and wants to know more, the details of the setup are in the regina-normal/aux repository: see packaging/windows/SETUP.txt.

I tried once a couple of years ago with the intel compiler under linux, and it broke badly enough that I didn’t pursue it. (However, I think the main problem was not enough c++14 and/or c++17 support.) But given that this conflict only arises in the presence of an independent installation of libnormaliz, I’m happy to leave the (intel compiler + independently installed libnormaliz on the CMAKE_INCLUDE_PATH) case unsupported for now.

- b.

[*] my own environment = the way I install things like gmp, Jansson, etc. locally; plus also my codesigning key ID is hard-coded in the project.

**Comment by WPettersson** [comment]
Okay, now that I think and look closer, we already do that (include `engine/` as the search path). And of course we do, since otherwise we would fail to compile since we couldn't find the include files. We need CMake to put it earlier on the command line, before the search location for other not-system-libraries.

**Comment by NathanDunfield** [comment]
@WPettersson Sorry for the slow response, I tried commit 6243397a78c4cac36189 in that branch but I am still getting the same error as before.

**Comment by WPettersson** [comment]
@NathanDunfield No problems. I'll set up a VM and actually try to replicate this issue, hopefully won't take too long.

**Comment by NathanDunfield** [comment]
If you want a premade VM, you could use [this Docker image](https://hub.docker.com/layers/computop/sage/9.5b7/images/sha256-4e364af835d291b31637e0ff4bdf88432b1fd24fc13b70af77e09d06d6a75ca4?context=explore), which was built using [this spec](https://github.com/3-manifolds/sagedocker/tree/master/sage).

**Comment by WPettersson** [comment]
Okay, I replicated the issue, and fixed it. There's one new commit (642df10ffb7dea29751feb02318c726b1f9e00eb) on the issue-73-libnormaliz-headers branch again. With this fix, the regina python shell starts up fine (whereas without it, it crashes as you noted). The C++ tests all pass fine, and the Python tests also pass (with the exception of any involving `Integer`, which won't pass as Regina doesn't export `Integer` when running under Sage to avoid clashing with Sage's `Integer` class). Hopefully this works for you.

Ben, this fix is now in the build process for Regina's Python module, but it'll also potentially arise for any build process where:
* Regina headers are included,
* libnormaliz headers are located in the same directory as headers for some other external package required by Regina (e.g., jansson or libtokyo), and
* this directory is not a standard include directory (e.g., /usr/include or similar depending on system).

Under this scenario, the compiler needs to be told to check the Regina header location before the "external" locations. This would apply to e.g. the GUI (which Nathan isn't building) and possibly the iOS apps. I don't know whether we want to cover those scenarios. It seems the engine is not susceptible, though. I'm guess that this is because if `"libnormaliz/general.h"` can be found by searching a parent of the current directory, that has precedent over "other location".

While digging, I also noticed that `enumerate/hilbertprimal-impl.h` includes a libnormaliz header: https://github.com/regina-normal/regina/blob/45a6a120420c5ec427824de0ff0144bdcea715f4/engine/enumerate/hilbertprimal-impl.h#L50

We don't ship that header, which technically means I think the shipped headers have been unusable for a while.
